/**
 * The verifiable draw pipeline over the RFC 9381 core in `@renaiss/ecvrf`
 * (ECVRF-EDWARDS25519-SHA512-ELL2, suite 0x04).
 *
 * Three layers live here — all application conventions, not part of the spec
 * (the spec-only code stays in `@renaiss/ecvrf`):
 *   1. Hex wrappers around the byte-level spec functions. All hex arguments
 *      and return values are viem `Hex` (0x-prefixed).
 *   2. β→stream expansion: one VRF output β expanded into a deterministic,
 *      publicly recomputable stream of floats in [0, 1).
 *   3. Draw resolution: the seed a single draw is committed to, and the
 *      eligible-card index its randomness resolves to.
 *
 * Public verification recipe (everything a third party needs):
 *   1. proof π is 80 octets: Gamma(32) ‖ c(16, LE) ‖ s(32, LE)
 *   2. ECVRF_verify(PK, α, π) per RFC 9381 §5.3 with suite 0x04
 *   3. β = ECVRF_proof_to_hash(π) — 64 octets
 *   4. stream draw i = low 53 bits of SHA-512(β ‖ i as 32-byte big-endian),
 *      over 2⁵³; a single card draw resolves to keccak256(β) mod remaining
 */

import { sha512 } from "@noble/hashes/sha2.js";
import { concatBytes } from "@noble/hashes/utils.js";
import {
  keygen,
  PI_LEN,
  proofToHash,
  prove,
  secretScalarAndPublicKey,
  verify,
} from "@renaiss/ecvrf";
import {
  bytesToHex,
  concat,
  hexToBigInt,
  hexToBytes,
  keccak256,
  stringToHex,
  type Hex,
} from "viem";

// ── hex wrappers around the RFC 9381 core ───────────────────────────────────

/** Generate a fresh VRF keypair, 0x-prefixed hex. */
export function ecvrfKeygen(): { sk: Hex; pk: Hex } {
  const { SK, pkString } = keygen();
  return { sk: bytesToHex(SK), pk: bytesToHex(pkString) };
}

/**
 * Derive the 32-byte RFC 8032 public key (hex) from a 32-byte secret key hex.
 * Used by verifiers (and tests) that have the private key but need the
 * matching public key to feed `ecvrfVerify`.
 */
export function ecvrfDerivePublicKey(privateKeyHex: Hex): Hex {
  const { Y } = secretScalarAndPublicKey(hexToBytes(privateKeyHex));
  return bytesToHex(Y.toBytes());
}

/** ECVRF_prove over hex: returns the 80-byte proof π and Gamma, 0x-prefixed. */
export function ecvrfProve(
  privateKeyHex: Hex,
  alphaHex: Hex,
): { proofHex: Hex; gammaHex: Hex } {
  const { piString, Gamma } = prove(
    hexToBytes(privateKeyHex),
    hexToBytes(alphaHex),
  );
  return {
    proofHex: bytesToHex(piString),
    gammaHex: bytesToHex(Gamma.toBytes()),
  };
}

/**
 * ECVRF_verify over hex. The verifier reproduces the seed derivation
 * off-chain (`alphaHex` is the α input to the VRF) and checks that `proofHex`
 * was generated by the holder of the private key corresponding to
 * `publicKeyHex`. Returns true iff the proof is valid.
 */
export function ecvrfVerify(
  publicKeyHex: Hex,
  alphaHex: Hex,
  proofHex: Hex,
): boolean {
  return ecvrfVerifyBeta(publicKeyHex, alphaHex, proofHex) !== null;
}

/**
 * ECVRF_verify over hex, returning the verified output β (64 bytes, hex) on
 * success and null for the spec's "INVALID" — including malformed hex input,
 * which never throws. Use this when the caller needs β itself (e.g. to
 * compare against a stored randomness value).
 */
export function ecvrfVerifyBeta(
  publicKeyHex: Hex,
  alphaHex: Hex,
  proofHex: Hex,
): Hex | null {
  try {
    const beta = verify(
      hexToBytes(publicKeyHex),
      hexToBytes(alphaHex),
      hexToBytes(proofHex),
    );
    return beta ? bytesToHex(beta) : null;
  } catch {
    // malformed hex input — the spec's "INVALID", never a throw
    return null;
  }
}

/** ECVRF_proof_to_hash over hex: β (64 bytes) from a valid proof. Throws on malformed proof. */
export function ecvrfProofToHash(proofHex: Hex): Hex {
  const proofBytes = hexToBytes(proofHex);
  if (proofBytes.length !== PI_LEN) {
    throw new Error("Invalid proof length for hashing");
  }
  const beta = proofToHash(proofBytes);
  if (beta === null) {
    throw new Error("Cannot hash proof: invalid Gamma component");
  }
  return bytesToHex(beta);
}

// ── VRF output expansion ─────────────────────────────────────────────────────
//
// A VRF evaluation yields ONE randomness β (64 octets for this ciphersuite).
// Many callers instead need a STREAM of values (e.g. an algorithm that draws
// repeatedly). These helpers expand a single β into a deterministic,
// reproducible stream of floats in [0, 1) using a public counter:
//
//   wordᵢ = SHA-512(β ‖ i as 32-byte big-endian)   (same hash as the suite)
//   rᵢ    = (wordᵢ as a big-endian integer mod 2⁵³) / 2⁵³
//
// Anyone can recompute any rᵢ from the (proof-authenticated) β, so every value
// is independently verifiable; nothing here is secret.

/** An injected source of randomness: () => float in [0, 1), like Math.random
 * but deterministic for a given β. */
export type Rng = () => number;

const TWO_POW_53 = BigInt(2) ** BigInt(53);

// The expansion index as a 32-byte big-endian octet string (RFC 8017 I2OSP).
function indexToBytes(index: number): Uint8Array {
  const out = new Uint8Array(32);
  let v = index;
  for (let i = 31; i >= 0 && v > 0; i--) {
    out[i] = v & 0xff;
    v = Math.floor(v / 256);
  }
  return out;
}

/**
 * The raw expansion word SHA-512(β ‖ i), as hex. Exposed so a verifier can
 * recompute any single draw by hand — hash β with the 32-byte big-endian
 * index, then apply the float formula in `randomAt` — making each value
 * independently checkable, not just trusted.
 */
export function randomWordHex(randomnessHex: Hex, index: number): Hex {
  return bytesToHex(
    sha512(concatBytes(hexToBytes(randomnessHex), indexToBytes(index))),
  );
}

/**
 * The i-th value derived from a VRF randomness β. Pure function of (β, index):
 * the k-th value of a stream MUST equal randomAt(β, k), so a verifier can
 * check any single draw on its own. `randomnessHex` is the VRF output, as
 * returned by `ecvrfProofToHash`.
 */
export function randomAt(randomnessHex: Hex, index: number): number {
  // low 53 bits of the word → [0, 1), matching a JS double's mantissa precision.
  return (
    Number(BigInt(randomWordHex(randomnessHex, index)) % TWO_POW_53) /
    Number(TWO_POW_53)
  );
}

/** A stream over β: successive randomAt(β, 0), randomAt(β, 1), … */
export function rngFromRandomness(randomnessHex: Hex): Rng {
  let i = 0;
  return () => randomAt(randomnessHex, i++);
}

/** Convenience (prover side): prove over α, then expose the rng + the
 * artifacts to publish. */
export function proveAndExpand(
  privateKeyHex: Hex,
  alphaHex: Hex,
): { rng: Rng; proofHex: Hex; randomnessHex: Hex } {
  const { proofHex } = ecvrfProve(privateKeyHex, alphaHex);
  const randomnessHex = ecvrfProofToHash(proofHex);
  return { rng: rngFromRandomness(randomnessHex), proofHex, randomnessHex };
}

/**
 * Convenience (verifier side): verify the proof against the public key, then
 * rebuild the identical rng. Returns null if the proof is invalid (β must not
 * be trusted then).
 */
export function verifyAndExpand(params: {
  publicKeyHex: Hex;
  alphaHex: Hex;
  proofHex: Hex;
}): Rng | null {
  const { publicKeyHex, alphaHex, proofHex } = params;
  if (!ecvrfVerify(publicKeyHex, alphaHex, proofHex)) return null;
  return rngFromRandomness(ecvrfProofToHash(proofHex));
}

// ── draw resolution ──────────────────────────────────────────────────────────
//
// A single card draw is committed to a seed derived from public inputs, and
// its verified randomness resolves to an index into the remaining eligible
// cards (sampled without replacement, lineup sorted by tokenId ascending,
// draws in checkout order).

/**
 * Domain-separation tag for the draw seed. Prepended as UTF-8 bytes so the
 * seed hash can never collide with any other keccak256 use. The pack id is
 * part of the preimage because a checkout id is only unique per pack.
 */
export const SEED_DOMAIN_TAG = "renaiss-gacha-v3-1";
const SEED_DOMAIN_TAG_HEX = stringToHex(SEED_DOMAIN_TAG);

/** α = keccak256(tag ‖ blockHash ‖ onChainPackId ‖ checkoutId as 32-byte BE). */
export const deriveDrawSeed = (
  blockHash: string,
  onChainPackId: string,
  checkoutId: number,
): Hex =>
  keccak256(
    concat([
      SEED_DOMAIN_TAG_HEX,
      blockHash as Hex,
      onChainPackId as Hex,
      `0x${checkoutId.toString(16).padStart(64, "0")}` as Hex,
    ]),
  );

/** The eligible-card index a draw's randomness resolves to:
 * keccak256(β) mod the number of remaining cards. */
export const deriveEligibleIndex = (
  randomnessHex: string,
  eligibleCount: number,
): number =>
  Number(hexToBigInt(keccak256(randomnessHex as Hex)) % BigInt(eligibleCount));
